/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCourierArgs } from "./CreateCourierArgs";
import { UpdateCourierArgs } from "./UpdateCourierArgs";
import { DeleteCourierArgs } from "./DeleteCourierArgs";
import { CourierCountArgs } from "./CourierCountArgs";
import { CourierFindManyArgs } from "./CourierFindManyArgs";
import { CourierFindUniqueArgs } from "./CourierFindUniqueArgs";
import { Courier } from "./Courier";
import { QuoteFindManyArgs } from "../../quote/base/QuoteFindManyArgs";
import { Quote } from "../../quote/base/Quote";
import { ShipmentFindManyArgs } from "../../shipment/base/ShipmentFindManyArgs";
import { Shipment } from "../../shipment/base/Shipment";
import { CourierService } from "../courier.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Courier)
export class CourierResolverBase {
  constructor(
    protected readonly service: CourierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "read",
    possession: "any",
  })
  async _couriersMeta(
    @graphql.Args() args: CourierCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Courier])
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "read",
    possession: "any",
  })
  async couriers(
    @graphql.Args() args: CourierFindManyArgs
  ): Promise<Courier[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Courier, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "read",
    possession: "own",
  })
  async courier(
    @graphql.Args() args: CourierFindUniqueArgs
  ): Promise<Courier | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Courier)
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "create",
    possession: "any",
  })
  async createCourier(
    @graphql.Args() args: CreateCourierArgs
  ): Promise<Courier> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Courier)
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "update",
    possession: "any",
  })
  async updateCourier(
    @graphql.Args() args: UpdateCourierArgs
  ): Promise<Courier | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Courier)
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "delete",
    possession: "any",
  })
  async deleteCourier(
    @graphql.Args() args: DeleteCourierArgs
  ): Promise<Courier | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Quote], { name: "quotes" })
  @nestAccessControl.UseRoles({
    resource: "Quote",
    action: "read",
    possession: "any",
  })
  async resolveFieldQuotes(
    @graphql.Parent() parent: Courier,
    @graphql.Args() args: QuoteFindManyArgs
  ): Promise<Quote[]> {
    const results = await this.service.findQuotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Shipment], { name: "shipments" })
  @nestAccessControl.UseRoles({
    resource: "Shipment",
    action: "read",
    possession: "any",
  })
  async resolveFieldShipments(
    @graphql.Parent() parent: Courier,
    @graphql.Args() args: ShipmentFindManyArgs
  ): Promise<Shipment[]> {
    const results = await this.service.findShipments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
